### ISSUE TITLE
[Bug] Layout breaking hover

### ISSUE THREAD

**Issue by 0xphilipp** [alleslabs/celatone-frontend#441]
https://github.com/alleslabs/celatone-frontend/assets/9350951/7de12bea-e368-49e6-bb61-e4d89a098c3d

**Comment by tansawit** [comment]
This is a necessary change we made quite a while back to prevent the row from splitting into two lines on hover and overall making it difficult/impossible to either click on the link or to copy.

Will keep it as is for now but might revisit in the future.
